site_name: 404 - A Privacy Tool
site_url: https://docs.404privacy.com
repo_url: https://github.com/un-nf/404

hooks:
  - hooks/release_metadata.py

nav: 
  - Home: index.md
  - Desktop: getStart/appStart.md
  - Self-Hosted/CLI:
    - dev/index.md
    - Windows: dev/windows.md
    - macOS: dev/macos.md
    - Linux: dev/linux.md
    - Developers: dev/developers.md
  - Developer Resources:
    - runtime/index.md
    - WSL Packaging: runtime/distro.md
    - Docker Pipeline: runtime/docker.md
    - --- References ---: resources/index.md
    - Repository Map: resources/repoDev.md
    - STATIC: resources/static.md
    - eBPF: resources/ebpf.md
    - API Documentation: resources/controlPlane.md
    - Profiles: resources/profiles.md
  - Overview:
    - Overview/index.md
    - What Does 404 Do?: Overview/whatIs.md
    - Why Do I Need 404?: Overview/why404.md
    - Understanding 404: Overview/architecture.md
  - FAQ: faq.md
  - Consent & Warning: consent.md
  - Contact Us: contact.md

theme:
  name: material
  font: false
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - content.tabs.link
    - toc.integrate

plugins:
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "35vw"
  - privacy
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

#emojis & icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Mermaid support
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Tabs support
  - pymdownx.tabbed:
      alternate_style: true

  - admonition

# !!! (???)
#    TEXT HERE

  - attr_list

# BUTTON
#     [Subscribe to our newsletter](#){ .md-button }

# Primary
#     [Subscribe to our newsletter](#){ .md-button .md-button--primary }

# w/ icon
#     [Send :fontawesome-solid-paper-plane:](#){ .md-button }

  - pymdownx.details # for admonition
  - pymdownx.superfences # for admonition + code highlighting
  - pymdownx.inlinehilite # for code highlighting
  - pymdownx.snippets # for code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
